name: tester
on: push
jobs:
  tester:
    runs-on: ubuntu-latest
    environment: dev
    env:
      CYPRESS_TESTUSER_PWD: ${{ secrets.SC_TESTUSER_PWD }}
      TESTER: ${{ vars.CYPRESS_TESTER }}
    steps:
      - name: check out repostitory
        uses: actions/checkout@v4
        with:
          ref: main
      - name: installatie NPM
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 16.17.0
      - run: npm ci
        shell: bash
      - name: acties
        shell: bash
        run: |
          echo waarde is $TESTER
          bin/verklap $CYPRESS_TESTUSER_PWD
          ln -s e2e cypress/integration
          curl https://frontend.staging.sduconnect.nl/nl/users/login
          npm run scripts -- --env TAGS="(@nu and not @ignore)" --env TESTUSER_PWD="${{ secrets.SC_TESTUSER_PWD }}"
      - run: echo "🍏 The status is ${{job.status}}."

